### ISSUE TITLE
Update the theme setting: omeka_version_constraint

### ISSUE THREAD

**Issue by Steve-A-Orr** [UniTasLibrary/omeka-bootstrap-theme#1]
Evidently this configuration doesn't actually mean that it work for any version greater than "1.0.0":
    `omeka_version_constraint = "^1.0.0"`

If you want it to work with Omeka S versions 2 and 3, then you must do something like: 
`omeka_version_constraint = "^1.0.0 || ^2.0.0 || ^3.0.0"`

I'm unsure if you've tested your theme in these versions of Omeka S, but I'm running 3.1.0 and when I made this change in my copy of your files it avoided the incompatibility error and allowed me to activate the theme.

**Comment by Monica-Wood** [comment]
Hi Steve.

Yes, this theme has only been tested up to version 1.4.  I have put it on a version 3 dev instance, but never fully tested it, so didn't want to assume it would work.
Thank you for letting me know that it works correctly for you, I will update the version constraint. 

Cheers!
Monica

**Comment by Monica-Wood** [comment]
I have finally gotten around to adding the support tags for the other versions.
