### ISSUE TITLE
Extra " quote in theme.ini

### ISSUE THREAD

**Issue by rschwab** [UniTasLibrary/omeka-bootstrap-theme#2]
Line 7 of config/theme.ini currently reads:
`omeka_version_constraint = "^1.0.0 || ^2.0.0 || ^3.0.0""`

But should read:
`omeka_version_constraint = "^1.0.0 || ^2.0.0 || ^3.0.0"`

**Comment by goetzk** [comment]
Hi @rschwab ,
Thanks for reporting that issue; I've just committed your suggested fix.

thanks,
